### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rookie-anoozzz**

### CODE REVIEW

**Comment by vatch123** [comment]
Only source files needed

**Comment by vatch123** [comment]
The folder of the files is also not correct

**Comment by rookie-anoozzz** [comment]
I have deleted the extra files . How to move the files to that folder ??

**Comment by vatch123** [comment]
Move the files in that folder on your local machine then push it to your fork. That will be all

**Comment by vatch123** [comment]
Still not in the correct directory. see how others have done it. You need to make a folder of our name and put all the files in it.

**Pull request merged**
